### ISSUE TITLE
how do i fix this im on linux 

### ISSUE THREAD

**Issue by blazingcody** [Mistervock/fnf-build-script#1]
RefreshEnv command not found
Error: Failed with error: No such Project : openfl
Error: Failed with error: No such Project : flixel
Error: Failed with error: No such Project : flixel-tools
Error: Failed with error: No such Project : flixel-addons
Error: Failed with error: No such Project : flixel-ui
Error: Failed with error: No such Project : hscript
Error: Failed with error: No such Project : flixel-addons

**Comment by Mistervock** [comment]
It's on windows. Sorry.

сб, 28 мая 2022 г., 0:37 blazingcody ***@***.***>:
